title: Barnabei Adventure Rentals
email: jmbarnabei@comcast.net
description: >-
  The advocatation site for the right to easy access to water at MSU.
baseurl: "/waterformsuwebsite"
url: ""

markdown: kramdown
